#!/bin/sh

cd "$(dirname "$0")/pre-commit.d"

for hook in *; do
    echo "${hook}"
    sh $hook
    RESULT=$?
    if [ $RESULT != 0 ]; then
        echo "pre-commit.d/$hook returned non-zero: $RESULT, abort commit"
        exit $RESULT
    fi
done

exit 0