# The name of the job, which will be displayed for the status check in PR.
name: Build success check

# Controls when the action will run.
# Below triggers the workflow on pull requests to `main`.
on:
  pull_request:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or
# in parallel.

jobs:
  build:
    runs-on: windows-latest
    name: Build all sample viewers
    env:
      WORKSPACE: ${{ github.workspace }}
    steps:
    - name: Clone .NET Samples
      uses: actions/checkout@v6

    - name: Build sample viewers
      shell: cmd
      run: tools\cibuild.cmd
