# The name of the job, which will be displayed for the status check in PR.
name: Build success check

# Controls when the action will run.
# Below triggers the workflow on pull requests to `main`.
on:
  pull_request:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or
# in parallel.

jobs:
# MAUI Build
  build-maui:
    runs-on: windows-latest
    name: MAUI Build
    steps:
    - name: Clone .NET Samples
      uses: actions/checkout@v6

    - name: Install MAUI Workload
      run: dotnet workload install maui

    - name: Setup dotnet
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: 8.0.x

    - name: Build MAUI (Windows)
      run: |
        dotnet build src\MAUI\Maui.Samples\ArcGIS.Samples.Maui.csproj -c Release -f net10.0-windows10.0.19041.0

    - name: Build MAUI (Android)
      run: |
        dotnet build src\MAUI\Maui.Samples\ArcGIS.Samples.Maui.csproj -c Release -f net10.0-android
    
    - name: Build MAUI (iOS)
      run: |
        dotnet build src\MAUI\Maui.Samples\ArcGIS.Samples.Maui.csproj -c Release -f net10.0-ios
    
    - name: Build MAUI (Mac)
      run: |
        dotnet build src\MAUI\Maui.Samples\ArcGIS.Samples.Maui.csproj -c Release -f net10.0-maccatalyst


# WPF .NET Build
  build-wpf:
    runs-on: windows-latest
    name: WPF .NET Build
    steps:
    - name: Clone .NET Samples
      uses: actions/checkout@v6
    
    - name: Setup dotnet
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: 8.0.x

    - name: Build WPF .NET
      run: |
        dotnet build src\WPF\WPF.Viewer\ArcGIS.WPF.Viewer.Net.csproj -c Release


# WinUI Build
  build-winUI:
    runs-on: windows-latest
    name: WinUI Build
    steps:
    - name: Clone .NET Samples
      uses: actions/checkout@v6
    
    - name: Setup dotnet
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: 8.0.x

    - name: Build WinUI
      run: |
        dotnet build src\WinUI\ArcGIS.WinUI.Viewer\ArcGIS.WinUI.Viewer.csproj -c Release -r win-x64
        dotnet build src\WinUI\ArcGIS.WinUI.Viewer\ArcGIS.WinUI.Viewer.csproj -c Release -r win-arm64
