# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET 6.0 Build Status

on:
  push:
    branches: [ "main", "v.next" ]
  pull_request:
    branches: [ "main", "v.next" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Build WPF Net 6.0
      run: dotnet build src/WPF/WPF.Viewer/ArcGIS.WPF.Viewer.Net.csproj
    - name: Build WinUI Net 6.0
      run: dotnet build src/WinUI/ArcGIS.WinUI.Viewer/ArcGIS.WinUI.Viewer.csproj
    - name: Build MAUI Net 6.0
      run: dotnet build src/MAUI/Maui.Samples/ArcGIS.Samples.Maui.csproj
