name: Sync v.next with main

on:
  push:
    branches:
      - wbohr/sync-branch-test

jobs:
  sync_branches:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Open PR
        run: |
            if ! git diff --quiet v.next; then
              echo "Git diff detected."
            else
              echo "No git diff detected."
            fi